name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: 4Xp2SLYc8p_xQgKVQb0d59MSg5cocqe9OIIssuomBkc
  DOCKER_BUILDKIT: true
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: "echo $FLY_API_TOKEN"
        - run: "flyctl deploy"

